name: Docs Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install python dependencies
        run: pip3 install jinja2==3.1.6 Pygments==2.19.1

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.13.2"

      - name: Build documentation
        run: |
          cmake -Sdocumentation -Bbuild
          cmake --build build --target GenerateDocs

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: documentation-html-${{ github.sha }}
          path: ./build/doxygen/html
