name: Windows

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Cache vcpkg binary packages
        uses: actions/cache@v3
        with:
          path: C:/Users/runneradmin/AppData/Local/vcpkg/archives
          key: ${{ github.workflow }}-vcpkg-curl-x64-windows
          restore-keys: ${{ github.workflow }}-vcpkg-curl-x64-windows

      - name: Install dependencies
        run: vcpkg install curl
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows

      - name: configure
        run: cmake -Stest -Bbuild -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: build
        run: cmake --build build --config Debug -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug

  build-standalone:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-standalone-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Cache vcpkg binary packages
        uses: actions/cache@v3
        with:
          path: C:/Users/runneradmin/AppData/Local/vcpkg/archives
          key: ${{ github.workflow }}-standalone-vcpkg-curl-x64-windows
          restore-keys: ${{ github.workflow }}-standalone-vcpkg-curl-x64-windows

      - name: Install dependencies
        run: vcpkg install curl
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows

      - name: configure
        run: cmake -Sstandalone -Bbuild-standalone -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: build
        run: cmake --build build-standalone --config Release -j4
